# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://myifeng.com
date_format: "ordinal"
title: 李啧啧_myifeng
subtitle: "myifeng's Personal Blog"
description: "Record ideas and knowledge"
keywords: Algorithm,Machine Learning(eg.Deep Learning),Data mining
#timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: myifeng
organization: HHIT
organization_url: http://myifeng.com
github_username: myifeng
location: Beijing，China
email: dengwenjun818@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home


  -
    href: /categories/
    label: Blog
   


  -
    href: /open-source/
    label: Open-source
   

  -
    href: /wiki/
    label: Wiki

  -
    href: /links/
    label: Link

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: myifeng/myifeng.github.io

# ---------------- # 
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
#comments_provider: gitalk
comments_provider: gitment


# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 

    
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: myifeng
    repo: blog-comments
    oauth:
        client_id: fce4dfc328494995f97c
        client_secret: 78fc6b732978acb4ecf405e1873f5c91002d8507
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: myifeng
    repo: blog-comments
    clientID: b0d6bb260b842b0838ce
    clientSecret: 2c44d50d184fa89a5d9977e134680b45a6a7addf
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-133556314-1

# ---------------- #
#    Counter     #
# ---------------- #
#使用的是learncloud，appid和key更换成自己的
leancloud:
  enable: true
  app_id: 5C0tQR6eaGhuceIV0gvUhkbJ-gzGzoHsz
  app_key: ElTbV0gVygY5GWTqtzMcotM7
